#######################################################
# 
# contact.py
# Python implementation of the Class contact
# Generated by Enterprise Architect
# Created on:      11-Feb-2020 11:08:08 AM
# Original author: Corvo
# 
#######################################################


class contact:
# default constructor       def __init__(self):  

    iconsetpath = "" 
     # iconsetpath getter 
     def geticonsetpath(self): 
      return self.iconsetpath 
 
     # iconsetpath setter 
     def seticonsetpath(iconsetpath=0):  
     self.iconsetpath=iconsetpath 
 
    callsign = "PirateRulez" 
     # callsign getter 
     def getcallsign(self): 
      return self.callsign 
 
     # callsign setter 
     def setcallsign(callsign=0):  
     self.callsign=callsign 
 
    endpoint = "" 
     # endpoint getter 
     def getendpoint(self): 
      return self.endpoint 
 
     # endpoint setter 
     def setendpoint(endpoint=0):  
     self.endpoint=endpoint 
     