#######################################################
#
# detail.py
# Python implementation of the Class detail
# Generated by Enterprise Architect
# Created on: 11-Feb-2020 11:08:07 AM
# Original author: Corvo
#
#######################################################


class Detail:
    """An optional element used to hold CoT sub-schema. empty element
    """
    def __init__(self, connType = None, chatType = None, senderCallsign = None, chatroom = None, groupOwner = None, id = None, parent = None, chatgrpuid0 = None, chatgrpuid1 = None, chatgrpid = None, arg10 = None, arg11 = None):
        argumentsRecieved = locals()

        args = self.createArguments(argumentsRecieved)

        case = {
            'chat': self.chatFunc
            }

        case[connType](args)
    def createArguments(self, argumentsRecieved):
        argumentsToBePassed = {}
        for x, y in argumentsRecieved.items():
            if x != 'self' and x != 'argumentsRecieved' and y != None:
                argumentsToBePassed[x] = y
            else:
                pass
        return argumentsToBePassed
    def chatFunc(self, info):
        from Model.chat import chat
        chat = chat(chatType = info['chatType'], senderCallsign = info['senderCallsign'] , chatroom = info['chatroom'], groupOwner = info['groupOwner'], id = info['id'], parent = info['parent'], chatgrpuid0 = info['chatgrpuid0'], chatgrpuid1 = info['chatgrpuid1'], chatgrpid = info['chatgrpid'])
        self.chat = chat