#######################################################
# 
# core_name_controller.py
# Python implementation of the Class domain
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:02 AM
# Original author: Giu Platania
# 
#######################################################
from digitalpy.core.main.controller import Controller

class DomainSenderController(Controller):
    """contains all the business logic of this core package
    """
# default constructor  def __init__(self):  

    def __init__(self, Request, Response, ActionMapper, Configuration):
        pass

    def broadcast_domain(self, Event):
        """this method will broadcast the component
        """
        pass
