#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from digitalpy.core.main.controller import Controller

class DomainGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(self, Request, Response, ActionMapper, Configuration):
        pass

    def serialize_domain(self):
        """this is the general method used to serialize the component to a given format
        """
        pass
