#######################################################
# 
# Detail.py
# Python implementation of the Class Detail
# Generated by Enterprise Architect
# Created on:      26-Sep-2020 9:41:25 PM
# Original author: natha
# 
#######################################################
from sqlalchemy import Column, ForeignKey
from FreeTAKServer.model.SQLAlchemy.Root import Base
from sqlalchemy import String
from sqlalchemy.orm import relationship
import FreeTAKServer.model.SQLAlchemy.CoTTables.Archive
import FreeTAKServer.model.SQLAlchemy.CoTTables._Group
import FreeTAKServer.model.SQLAlchemy.CoTTables.Chat
import FreeTAKServer.model.SQLAlchemy.CoTTables.Color
import FreeTAKServer.model.SQLAlchemy.CoTTables.Contact
import FreeTAKServer.model.SQLAlchemy.CoTTables.Dest
import FreeTAKServer.model.SQLAlchemy.CoTTables.Emergency
import FreeTAKServer.model.SQLAlchemy.CoTTables.Link
import FreeTAKServer.model.SQLAlchemy.CoTTables.Marti
import FreeTAKServer.model.SQLAlchemy.CoTTables.Precisionlocation
import FreeTAKServer.model.SQLAlchemy.CoTTables.Remarks
import FreeTAKServer.model.SQLAlchemy.CoTTables.Serverdestination
import FreeTAKServer.model.SQLAlchemy.CoTTables.Status
import FreeTAKServer.model.SQLAlchemy.CoTTables.Summary
import FreeTAKServer.model.SQLAlchemy.CoTTables.Takv
import FreeTAKServer.model.SQLAlchemy.CoTTables.Track
import FreeTAKServer.model.SQLAlchemy.CoTTables.Uid
import FreeTAKServer.model.SQLAlchemy.CoTTables.Usericon



class Detail(Base):
# default constructor  def __init__(self):
    __tablename__ = 'Detail'
    PrimaryKey = Column(ForeignKey("Event.uid"), primary_key=True)
    xmlString = Column(String)
    archive = relationship("Archive", uselist=False)
    #_group = relationship("_Group", uselist=False, back_populates="parent")
    chat = relationship("Chat", uselist=False)
    color = relationship("Color", uselist=False)
    contact = relationship("Contact", uselist=False)
    emergency = relationship("Emergency", uselist=False)
    link = relationship("Link", uselist=False)
    marti = relationship("Marti", uselist=False)
    precisionlocation = relationship("Precisionlocation", uselist=False)
    remarks = relationship("Remarks", uselist=False)
    serverdestination = relationship("Serverdestination", uselist=False)
    status = relationship("Status", uselist=False)
    summary = relationship("Summary", uselist=False)
    takv = relationship("Takv", uselist=False)
    track = relationship("Track", uselist=False)
    uid = relationship("Uid", uselist=False)
    usericon = relationship("Usericon", uselist=False)

