#######################################################
# 
# contact.py
# Python implementation of the Class contact
# Generated by Enterprise Architect
# Created on:      10-Feb-2020 3:10:07 PM
# Original author: Giu Platania
# 
#######################################################


class contact:

    callsign = "PirateRulez"
    iconsetpath = ""
    endpoint = ""