#######################################################
# 
# Event2.py
# Python implementation of the Class Event
# Generated by Enterprise Architect
# Created on:      10-Feb-2020 3:10:06 PM
# Original author: Giu Platania
# 
#######################################################
from TAKfreeServer.Model.point import point
from TAKfreeServer.Model.detail import detail

    """represent a TAK event: this class is instantiated with a standard set of values.
    """
class Event:
    """represent a TAK event: this class is instantiated with a standard set of values.
    """
    m_point = point()
    m_detail = detail()
    # Gives a hint about how the coordinates were generated
    __how = m-g
    # Schema version of this event instance (e.g. 2.0)
    __version = 2.0
    # time stamp: when the event was generated
    __time = 2020-06-08T18:19:40.000Z
    # <font color="#008000">Hierarchically organized hint about event type</font>
    __type = a-h-G-E-V
    # ending time when an event should no longer be considered valid
    __stale = 2020-06-08T18:19:40.000Z
    # Globally unique name for this information on this event
    __uid = UIDString
    # starting time when an event  should be considered valid
    __Start = 2020-06-08T18:19:40.000Z