#######################################################
# 
# Event.py
# Python implementation of the Class Event
# Generated by Enterprise Architect
# Created on:      07-Feb-2020 10:19:59 AM
# Original author: Giu Platania
# 
#######################################################
from class.point import point
from class.detail import detail

class Event:
    """represent a TAK event
    """
    m_point= point()





    m_detail= detail()



    # Gives a hint about how the coordinates were generated
    __how = m-g
    # Schema version of this event instance (e.g. 2.0)
    __version = 2.0
    # time stamp: when the event was generated
    __time = 
    __type = a-h-G-E-V

