#######################################################
# 
# takv.py
# Python implementation of the Class takv
# Generated by Enterprise Architect
# Created on:      10-Feb-2020 3:10:08 PM
# Original author: Giu Platania
# 
#######################################################


class takv:
    # the variant of TAK
    __platform = ATAK-CIV
    # type of physical device
    __device = "Pirate Device" Device
    # the operating system running TAK
    __os = Linux
    # the version of TAK running on the device
    __version = 3.12.0-45691.45691-CIV