# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiResponseEntryIntegerIntegerData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: int=None, key: int=None):  # noqa: E501
        """ApiResponseEntryIntegerIntegerData - a model defined in Swagger

        :param value: The value of this ApiResponseEntryIntegerIntegerData.  # noqa: E501
        :type value: int
        :param key: The key of this ApiResponseEntryIntegerIntegerData.  # noqa: E501
        :type key: int
        """
        self.swagger_types = {
            'value': int,
            'key': int
        }

        self.attribute_map = {
            'value': 'value',
            'key': 'key'
        }
        self._value = value
        self._key = key

    @classmethod
    def from_dict(cls, dikt) -> 'ApiResponseEntryIntegerIntegerData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiResponseEntryIntegerInteger_data of this ApiResponseEntryIntegerIntegerData.  # noqa: E501
        :rtype: ApiResponseEntryIntegerIntegerData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this ApiResponseEntryIntegerIntegerData.


        :return: The value of this ApiResponseEntryIntegerIntegerData.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this ApiResponseEntryIntegerIntegerData.


        :param value: The value of this ApiResponseEntryIntegerIntegerData.
        :type value: int
        """

        self._value = value

    @property
    def key(self) -> int:
        """Gets the key of this ApiResponseEntryIntegerIntegerData.


        :return: The key of this ApiResponseEntryIntegerIntegerData.
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key: int):
        """Sets the key of this ApiResponseEntryIntegerIntegerData.


        :param key: The key of this ApiResponseEntryIntegerIntegerData.
        :type key: int
        """

        self._key = key
