# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AuthServer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, issuer: str=None):  # noqa: E501
        """AuthServer - a model defined in Swagger

        :param issuer: The issuer of this AuthServer.  # noqa: E501
        :type issuer: str
        """
        self.swagger_types = {
            'issuer': str
        }

        self.attribute_map = {
            'issuer': 'issuer'
        }
        self._issuer = issuer

    @classmethod
    def from_dict(cls, dikt) -> 'AuthServer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthServer of this AuthServer.  # noqa: E501
        :rtype: AuthServer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def issuer(self) -> str:
        """Gets the issuer of this AuthServer.


        :return: The issuer of this AuthServer.
        :rtype: str
        """
        return self._issuer

    @issuer.setter
    def issuer(self, issuer: str):
        """Sets the issuer of this AuthServer.


        :param issuer: The issuer of this AuthServer.
        :type issuer: str
        """

        self._issuer = issuer
