# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.checklist_task import ChecklistTask  # noqa: F401,E501
from swagger_server import util


class ChecklistTasks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, checklist_task: List[ChecklistTask]=None):  # noqa: E501
        """ChecklistTasks - a model defined in Swagger

        :param checklist_task: The checklist_task of this ChecklistTasks.  # noqa: E501
        :type checklist_task: List[ChecklistTask]
        """
        self.swagger_types = {
            'checklist_task': List[ChecklistTask]
        }

        self.attribute_map = {
            'checklist_task': 'checklistTask'
        }
        self._checklist_task = checklist_task

    @classmethod
    def from_dict(cls, dikt) -> 'ChecklistTasks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChecklistTasks of this ChecklistTasks.  # noqa: E501
        :rtype: ChecklistTasks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def checklist_task(self) -> List[ChecklistTask]:
        """Gets the checklist_task of this ChecklistTasks.


        :return: The checklist_task of this ChecklistTasks.
        :rtype: List[ChecklistTask]
        """
        return self._checklist_task

    @checklist_task.setter
    def checklist_task(self, checklist_task: List[ChecklistTask]):
        """Sets the checklist_task of this ChecklistTasks.


        :param checklist_task: The checklist_task of this ChecklistTasks.
        :type checklist_task: List[ChecklistTask]
        """
        if checklist_task is None:
            raise ValueError("Invalid value for `checklist_task`, must not be `None`")  # noqa: E501

        self._checklist_task = checklist_task
