# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.checklist_column import ChecklistColumn  # noqa: F401,E501
from swagger_server import util


class ChecklistColumns(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, checklist_column: List[ChecklistColumn]=None):  # noqa: E501
        """ChecklistColumns - a model defined in Swagger

        :param checklist_column: The checklist_column of this ChecklistColumns.  # noqa: E501
        :type checklist_column: List[ChecklistColumn]
        """
        self.swagger_types = {
            'checklist_column': List[ChecklistColumn]
        }

        self.attribute_map = {
            'checklist_column': 'checklistColumn'
        }
        self._checklist_column = checklist_column

    @classmethod
    def from_dict(cls, dikt) -> 'ChecklistColumns':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChecklistColumns of this ChecklistColumns.  # noqa: E501
        :rtype: ChecklistColumns
        """
        return util.deserialize_model(dikt, cls)

    @property
    def checklist_column(self) -> List[ChecklistColumn]:
        """Gets the checklist_column of this ChecklistColumns.


        :return: The checklist_column of this ChecklistColumns.
        :rtype: List[ChecklistColumn]
        """
        return self._checklist_column

    @checklist_column.setter
    def checklist_column(self, checklist_column: List[ChecklistColumn]):
        """Sets the checklist_column of this ChecklistColumns.


        :param checklist_column: The checklist_column of this ChecklistColumns.
        :type checklist_column: List[ChecklistColumn]
        """
        if checklist_column is None:
            raise ValueError("Invalid value for `checklist_column`, must not be `None`")  # noqa: E501

        self._checklist_column = checklist_column
