# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Endpoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, callsign: str=None):  # noqa: E501
        """Endpoint - a model defined in Swagger

        :param name: The name of this Endpoint.  # noqa: E501
        :type name: str
        :param callsign: The callsign of this Endpoint.  # noqa: E501
        :type callsign: str
        """
        self.swagger_types = {
            'name': str,
            'callsign': str
        }

        self.attribute_map = {
            'name': 'name',
            'callsign': 'callsign'
        }
        self._name = name
        self._callsign = callsign

    @classmethod
    def from_dict(cls, dikt) -> 'Endpoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Endpoint of this Endpoint.  # noqa: E501
        :rtype: Endpoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Endpoint.


        :return: The name of this Endpoint.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Endpoint.


        :param name: The name of this Endpoint.
        :type name: str
        """

        self._name = name

    @property
    def callsign(self) -> str:
        """Gets the callsign of this Endpoint.


        :return: The callsign of this Endpoint.
        :rtype: str
        """
        return self._callsign

    @callsign.setter
    def callsign(self, callsign: str):
        """Sets the callsign of this Endpoint.


        :param callsign: The callsign of this Endpoint.
        :type callsign: str
        """

        self._callsign = callsign
