# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Streamingbroker(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, enable: bool=None):  # noqa: E501
        """Streamingbroker - a model defined in Swagger

        :param enable: The enable of this Streamingbroker.  # noqa: E501
        :type enable: bool
        """
        self.swagger_types = {
            'enable': bool
        }

        self.attribute_map = {
            'enable': 'enable'
        }
        self._enable = enable

    @classmethod
    def from_dict(cls, dikt) -> 'Streamingbroker':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Streamingbroker of this Streamingbroker.  # noqa: E501
        :rtype: Streamingbroker
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enable(self) -> bool:
        """Gets the enable of this Streamingbroker.


        :return: The enable of this Streamingbroker.
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable: bool):
        """Sets the enable of this Streamingbroker.


        :param enable: The enable of this Streamingbroker.
        :type enable: bool
        """

        self._enable = enable
