#######################################################
# 
# CoreNameRules.py
# Python implementation of the Class CoreNameRules
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:09 AM
# Original author: Giu Platania
# 
#######################################################


class COTManagementRules:
# default constructor  def __init__(self):  

    pass
