#######################################################
#
# detail.py
# Python implementation of the Class detail
# Generated by Enterprise Architect
# Created on: 11-Feb-2020 11:08:07 AM
# Original author: Corvo
#
#######################################################
import controllers.RequestCOTController

class detail:
    """An optional element used to hold CoT sub-schema. empty element
    """
    def __init__(self):
        a= 1
