#######################################################
# 
# ManageRadacatMessageController.py
# Python implementation of the Class ManageRadacatMessageController
# Generated by Enterprise Architect
# Created on:      15-Apr-2020 4:57:05 PM
# Original author: Giu Platania
# 
#######################################################


class ManageRadacatMessageController:
# default constructor  def __init__(self):  

    def End():
        pass

    def ManageRadacatMessage_ActivityGraph():
        pass

    def ReceiveRadacatChat():
        pass

    def ReceiveRadacatChatLocation():
        pass

    def Start():
        pass