#######################################################
# 
# RequestCOTController.py
# Python implementation of the Class RequestCOTController
# Generated by Enterprise Architect
# Created on:      26-Mar-2020 6:32:34 PM
# Original author: Giu Platania
# 
#######################################################
import os,sys,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir) 
from Model.Event import Event
from constant import vars as con
conn = con()

class RequestCOTController:
    """this controller manage all the different types of COTS, including the geochat
    """
# default constructor  
    def __init__(self):  
        a = 1
    def ping(self, lat, lon):
       event = Event(conn.PING, lat, lon) 
       return event

    def chat(self, chatType = None, senderCallsign = None, chatroom = None, groupOwner = None, id = None, parent = None, chatgrpuid0 = None, chatgrpuid1 = None, chatgrpid = None):
        event = Event(connType = 'chat', chatType = chatType, senderCallsign = senderCallsign, chatroom = chatroom, groupOwner = groupOwner, id = id, parent = parent, chatgrpuid0 = chatgrpuid0, chatgrpuid1 = chatgrpuid1, chatgrpid = chatgrpid)
        return event
