#######################################################
# 
# ClientSendHandeler.py
# Python implementation of the Class ClientSendHandeler
# Generated by Enterprise Architect
# Created on:      21-May-2020 9:46:48 AM
# Original author: Natha Paquette
# 
#######################################################


class ClientSendHandeler:
# default constructor  def __init__(self):  

    def attemptToSendData():
        pass

    def monitorDataQueue():
        pass

    def serializeModelObject():
        pass