#######################################################
# 
# Emergency.py
# Python implementation of the Class Emergency
# Generated by Enterprise Architect
# Created on:      04-Nov-2020 4:26:40 PM
# Original author: natha
# 
#######################################################
from FreeTAKServer.model.RestMessages.RestEnumerations import RestEnumerations

class Emergency:
# default constructor  def __init__(self):  

    # the type of emergency to be displayed
    emergencyType = ""
    # the name of the person that has an emergency.
    name = ""
    # server generated Unique Id of this emergency
    uid = ""
    latitude = ''
    longitude = ''