from FreeTAKServer.components.core.abstract_component.cot_node import CoTNode
from FreeTAKServer.components.core.abstract_component.cot_property import CoTProperty
from FreeTAKServer.model.FTSModel.fts_protocol_object import FTSProtocolObject
#######################################################
# 
# Precisionlocation.py
# Python implementation of the Class Precisionlocation
# Generated by Enterprise Architect
# Created on(FTSProtocolObject):      11-Feb-2020 11(FTSProtocolObject):08(FTSProtocolObject):10 AM
# Original author: Corvo
# 
#######################################################
from FreeTAKServer.model.FTSModelVariables.PrecisionlocationVariables import PrecisionlocationVariables as vars

class precisionlocation(CoTNode):
    """some type of location?
    """
    
# TDB can be DTED0 or ???
 

    def __init__(self, configuration, model, altsrc=vars().ALTSRC, geopointsrc=vars().GEOPOINTSRC):
        super().__init__(self.__class__.__name__, configuration, model)
        self.cot_attributes['geopointsrc'] = geopointsrc
        self.cot_attributes['altsrc'] = altsrc

    @CoTProperty
    def geopointsrc(self): 
      return self.cot_attributes.get('geopointsrc', None)
 
    @geopointsrc.setter
    def geopointsrc(self, geopointsrc=0):  
        self.cot_attributes['geopointsrc'] = geopointsrc
    
    @CoTProperty
    def altsrc(self): 
        return self.cot_attributes.get('altsrc', None)
 
    @altsrc.setter
    def altsrc(self, altsrc=0):  
        self.cot_attributes['altsrc'] = altsrc
 