#######################################################
# 
# activeThreads.py
# Python implementation of the Class activeThreads
# Generated by Enterprise Architect
# Created on:      21-May-2020 10:18:14 AM
# Original author: Natha Paquette
# 
#######################################################


class activeThreads:
# default constructor  def __init__(self):  

    ThreadArray = []