#######################################################
# 
# RequestCOTController.py
# Python implementation of the Class RequestCOTController
# Generated by Enterprise Architect
# Created on:      26-Mar-2020 6:32:34 PM
# Original author: Giu Platania
# 
#######################################################
from Model.Event import Event as Event
class RequestCOTController:
    """this controller manage all the different types of COTS, including the geochat
    """
# default constructor  
    def __init__(self):  
        a = 1
    def dropPin(self):
       event = Event('dropPin', 123, 123)

    def sendGeoChatToAllChatRooms(self):
        event = Event('GeoToAllRooms', messagetext, callsign)

    def sendGeoChatToGroup(self):
        event = Event('GeoToGroup', messagetext, callsign)

    def sendGeoChatToTeam(self):
        """this will send the geochat to team
        """
        event = Event('GeoToTeam', messagetext, callsign)
