name: Upload Python Package

on:
  release:
    types: [created]
    
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools poetry
    - name: Build and publish
      env:
        POETRY_HTTP_BASIC_DEV_USERNAME: ${{ secrets.PYPI_USERNAME }}
        POETRY_HTTP_BASIC_DEV_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --build